'@context': null
ontologies:
  - id: pcl
    preferredPrefix: PCL
    title: PCL Ontology
    description: Cell types that are provisionally defined by experimental techniques such as single cell or single nucleus transcriptomics rather than a straightforward & coherent set of properties. 
    uri: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl-full.owl
    base_uri:
      - http://purl.obolibrary.org/obo/PCL_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    preferred_root_term:
      - http://purl.obolibrary.org/obo/CL_0000000
    reasoner: EL
 #   oboSlims: false
    ontology_purl: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl-full.owl
    allow_download: false
    
  - id: bds1
    preferredPrefix: BDS
    title: BDS Ontology
    description: "BDS Ontology - marker based"
    uri: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/ec_denormalised_markers/bdscratch-full.owl
    base_uri:
      - http://brain_data_standards/scratch_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    preferred_root_term:
      - http://purl.obolibrary.org/obo/CL_0011005
      - http://purl.obolibrary.org/obo/CL_0000679
      - http://purl.obolibrary.org/obo/CL_4023065
      - http://purl.obolibrary.org/obo/CL_0002453
      - http://purl.obolibrary.org/obo/CL_0000127
      - http://purl.obolibrary.org/obo/CL_0000128
      - http://purl.obolibrary.org/obo/CL_0000115
      - http://purl.obolibrary.org/obo/CL_4023051
      - http://purl.obolibrary.org/obo/CL_0002590
      - http://purl.obolibrary.org/obo/CL_2000043
      - http://purl.obolibrary.org/obo/CL_0000129
      - http://purl.obolibrary.org/obo/CL_0000881 
    reasoner: EL
  #  oboSlims: false
    ontology_purl: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/master/bdscratch-full.owl
    allow_download: false
    
  - id: bds2
    preferredPrefix: BDS
    title: BDS Ontology
    description: "BDS Ontology - taxonomy based"
    uri: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/pcl_migration/bdso-full.owl
    base_uri:
      - http://brain_data_standards/scratch_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    preferred_root_term:
      - http://purl.obolibrary.org/obo/CL_0011005
      - http://purl.obolibrary.org/obo/CL_0000679
      # Add CL for Meis2
      - http://purl.obolibrary.org/obo/CL_0002453
      - http://purl.obolibrary.org/obo/CL_0002605
      - http://purl.obolibrary.org/obo/CL_0000128
      - http://purl.obolibrary.org/obo/CL_1001602
      # Add CL for VLMC here
      - http://purl.obolibrary.org/obo/CL_0002590
      - http://purl.obolibrary.org/obo/CL_2000043
      - http://purl.obolibrary.org/obo/CL_0000129
    reasoner: EL
  #  oboSlims: false
    ontology_purl: https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/pcl_migration/bdso-full.owl
    allow_download: false

#  - id: bds_subset
#    preferredPrefix: BDS_S
#    title: BDS Subset
#    description: BDS Subset description.
#    uri: https://raw.githubusercontent.com/obophenotype/cell-ontology/master/src/ontology/subsets/BDS_subset.owl
#    base_uri:
#      - http://purl.obolibrary.org/obo/BFO_
#    synonym_property:
#      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
#    definition_property:
#      - http://purl.obolibrary.org/obo/IAO_0000115
#    preferred_root_term:
#      - http://purl.obolibrary.org/obo/CL_0011005
#      - http://purl.obolibrary.org/obo/CL_0000679
#      # Add CL for Meis2
#      - http://purl.obolibrary.org/obo/CL_0002453
#      - http://purl.obolibrary.org/obo/CL_0002605
#      - http://purl.obolibrary.org/obo/CL_0000128
#      - http://purl.obolibrary.org/obo/CL_1001602
#      # Add CL for VLMC here
#      - http://purl.obolibrary.org/obo/CL_0002590
#      - http://purl.obolibrary.org/obo/CL_2000043
#      - http://purl.obolibrary.org/obo/CL_0000129
#    reasoner: EL
#    ontology_purl: https://raw.githubusercontent.com/obophenotype/cell-ontology/master/src/ontology/subsets/BDS_subset.owl
#    allow_download: false
#    
#  - id: bds_cell
#    preferredPrefix: BDS_C
#    title: BDS Cell Ontology
#    description: "BDS Ontology - autocomplete demo"
#    uri: https://raw.githubusercontent.com/obophenotype/bds-pipeline-config/dev/config/demo/bdscratch-cell.owl
#    base_uri:
#      - http://brain_data_standards/scratch_
#    synonym_property:
#      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
#    definition_property:
#      - http://purl.obolibrary.org/obo/IAO_0000115
#    preferred_root_term:
#      - http://purl.obolibrary.org/obo/CL_0011005
#      - http://purl.obolibrary.org/obo/CL_0000679
#      # Add CL for Meis2
#      - http://purl.obolibrary.org/obo/CL_0002453
#      - http://purl.obolibrary.org/obo/CL_0002605
#      - http://purl.obolibrary.org/obo/CL_0000128
#      - http://purl.obolibrary.org/obo/CL_1001602
#      # Add CL for VLMC here
#      - http://purl.obolibrary.org/obo/CL_0002590
#      - http://purl.obolibrary.org/obo/CL_2000043
#      - http://purl.obolibrary.org/obo/CL_0000129
#    reasoner: EL
#  #  oboSlims: false
#    ontology_purl: https://raw.githubusercontent.com/obophenotype/bds-pipeline-config/dev/config/demo/bdscratch-cell.owl
#    allow_download: false

  - id: npo
    preferredPrefix: npo
    title: Neuron phenotype ontology
    description: Neuron phenotype ontology
    uri: https://raw.githubusercontent.com/SciCrunch/NIF-Ontology/neurons/ttl/bridge/neuron-bridge.ttl
    base_uri:
      - http://uri.interlex.org/npo/uris/neurons/
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    preferred_root_term:
      - http://uri.interlex.org/tgbugs/uris/readable/NeuronCUT
      - http://uri.interlex.org/tgbugs/uris/readable/NeuronEBM
    reasoner: EL
    ontology_purl: https://raw.githubusercontent.com/SciCrunch/NIF-Ontology/neurons/ttl/bridge/neuron-bridge.ttl
    allow_dowload: false

#  - id: 
#    preferredPrefix: 
#    title: 
#    description: 
#    uri: 
#    base_uri:
#      - 
#    synonym_property:
#      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
#    definition_property:
#      - http://purl.obolibrary.org/obo/IAO_0000115
#    ontology_purl:
#    allow_dowload: False
